CREATE OR REPLACE VIEW {MD_EVA}.v_tenspdpi
(
	cod_piclient COMMENT 'Identificador del Codigo de cliente de la visita. (Incluye Codigos de cliente, grupos, grupo sieble, contrapartidas, clientes ficticios PROS o confidenciales.) [[12540]]'
    ,des_piclient COMMENT 'Descripcion que incluye el Codigo de cliente visitado, relacionado con su cod cliente. [[5647]]'
    ,des_piaccion COMMENT 'Descripcion que identifica si el cliente es grupo (Parent) o cliente (subsidiary) [[17869]]'
    ,des_industri COMMENT 'Descripcion de la industria a la que pertenece el cliente.  [[2181]]'
    ,des_pisector COMMENT 'Representa un nivel por encima de Industria (subsector). Es el sector Cib (Actividad agrupada) al que pertenece el cliente.'
    ,des_paiscl COMMENT 'Descripcion del pais del cliente.  [[12575]]'
    ,cod_pigrupo COMMENT 'Codigo identificativo del grupo al que pertenece el cliente.  [[3290]]'
    ,des_pigrupo COMMENT 'Nombre del grupo al que pertenece el cliente. [[3291]]'
    ,des_paisgrup COMMENT 'Descripcion del pais al que pertenece el cliente. [[12575]]'
    ,des_paisges COMMENT 'DESCRIPCION DEL PAIS DE GESTION DE UN GRUPO EMPRESARIAL [[17036]]'
    ,des_pisegmen COMMENT 'Descripcion del segmento al que pertenece el grupo.'
    ,des_pisubseg COMMENT 'Descripcion del subsegmento. Procedente de su aplicacion, no coincide con plataforma. No usado.'
    ,des_tier COMMENT 'Descripcion del nivel al que pertenece el grupo. Ej: CIB-PLATINUM, CIB-GOLD  [[17048]]'
    ,cod_userlasm COMMENT 'Codigo de usuario de la tecltima modificacion de la oportunidad de negocio. [[18152]]'
    ,des_userlasm COMMENT 'Nombre de usuario de la tecltima modificacion de la oportunidad de negocio.'
    ,des_fecmodu COMMENT 'Fecha de la tecltima modificacion de la oportunidad de negocio. VA'
    ,cod_dboportu COMMENT 'Codigo que identifica  a la oportunidad de negocio. VA [[17763]]'
    ,des_tipoconf COMMENT 'Descripcion que identifica si la oportunidad de negocio es confidencial o no. [[17766]]'
    ,des_nproycon COMMENT 'Si la oportunidad de negocio es confidencial se asigna un nombre de proyecto.'
    ,des_pipartic COMMENT 'Participantes si la oportunidad es confidencial.'
    ,cod_pubcompl COMMENT 'Indica si la publicacion ha pasado el cumplimiento. Yes o no.'
    ,des_catprod COMMENT 'Proporciona informacion de la categoria'
    ,des_piproduc COMMENT 'Descripcion del producto asociado a la oportunidad de negocio.'
    ,des_fecentr COMMENT 'Fecha de entrada en el sistema de la oportunidad de negocio. [[17768]]'
    ,des_feccest COMMENT 'Fecha en la que se estima se cerrara el acuerdo en la oportunidad de negocio. [[17771]]'
    ,cod_dvisita COMMENT 'Identificador unico del Codigo de visita del sistema origen. Puede contener el valor Confidencial.  [[17784]]'
    ,des_fecvisi COMMENT 'Fecha en la que se realiza la visita.  [[17786]]'
    ,des_cusebbva COMMENT 'Codigo que identifica al patrocinador o patrocinadores con usuario del BBVA. (separados por comas.)'
    ,des_userbbva COMMENT 'Nombre o nombres de los patrocinadores de BBVA.'
    ,des_otherusr COMMENT 'Otros Codigos de usuario a tener en cuenta.'
    ,des_othernam COMMENT 'Nombres de otros usuarios de BBVA de interes en la oportunidad.'
    ,des_qnuingr COMMENT 'Ingresos esperados por la oportunidad de negocio.'
    ,cod_pimoneda COMMENT 'Indica la moneda en la que viene los ingresos esperados.'
    ,des_feciden COMMENT 'Fecha en que la oportunidad de negocio fue identificada.  [[17770]]'
    ,des_fecdisc COMMENT 'Fecha de discusion con cliente.  [[17769]]'
    ,des_estgbopp COMMENT 'Descripcion del estado de la oportunidad de negocio, esta puede estar:  - Opportunity accepted  - Opportunity alive  - Opportunity missed [[17755]]'
    ,des_fecestg COMMENT 'Fecha que aplica al estado global de la oportunidad de negocio.  [[17872]]'
    ,des_reginal COMMENT 'Informacion de la region en la que se encuentra la oportunidad'
    ,cod_traglobb COMMENT 'Indica (Yes o No) si es seguida por el GLOBAL BANKER. (Subsidiaries Plan)'
    ,cod_crossflg COMMENT 'Indica si es venta cruzada (Yes o no)'
    ,des_crossdes COMMENT 'Descripcion de la venta cruzada.'
    ,des_qnucrre COMMENT 'Ingreso esperado por la venta cruzada.'
    ,cod_crossmod COMMENT 'Modeda del Ingreso esperado por la venta cruzada.'
    ,des_qnucrrc COMMENT 'Ingresos esperados por ventas cruzadas en la moneda actual. CROSS SSELLING EXPERATED REVENUES CURRENT RC'
    ,des_pinextst COMMENT 'Nuevos pasos especificados en la siguiente reunion. = [[17871]]'
    ,des_fecremo COMMENT 'Fecha de borrado oportunidad'
    ,cod_userglob COMMENT 'CODIGO DEL USUARIO GLOBAL BANKER Ejemplos: UA80042, UB24383, etc  [[12631]]'
    ,cod_luserpip COMMENT 'Codigo de usuario de tecltima modificacion de la Pipeline.  [[18142]]'
    ,des_luserpip COMMENT 'Nombre de usuario de tecltima modificacion de la Pipeline.'
    ,des_fecmpip COMMENT 'Fecha de usuario de tecltima modificacion de la Pipeline.'
    ,cod_dpipelin COMMENT 'Codigo identificativo de la Pipeline.  [[17764]]'
    ,des_prodcuno COMMENT 'Descripcion de la categoria de producto a primer nivel.  [[3]]'
    ,des_prodcdos COMMENT 'Descripcion de la categoria de productos a segundo nivel.  [[7]]'
    ,cod_psponsor COMMENT 'Codigo del patrocinador del producto registrado en plataforma. Puede venir confidencial.'
    ,des_psponsor COMMENT 'Descripcion del nombre del patrocinador del producto registrado en plataforma. Puede venir confidencial.'
    ,cod_pdsponso COMMENT 'Codigo de usuario del patrocinador delegado del producto registrado en la plataforma.'
    ,des_pdsponso COMMENT 'Descripcion del nombre de patrocinador delegado del producto, registrado en plataforma.'
    ,cod_sedegeog COMMENT 'Codigo de Booking Entity. Equivalente al concepto de Sede. [[20122]]'
    ,des_sedeg COMMENT 'Descripcion del Booking Entity. Equivalente a la Descripcion del concepto de Sede.'
    ,des_fecrisk COMMENT 'Fecha de validacion por riesgo. Relacionada con el estado de la pipeline. [[17772]]'
    ,des_fecoffe COMMENT 'Fecha de cuando se oferto la oportunidad de negocio. Relacionada con el estado de la pipeline.  [[17773]]'
    ,des_fecmand COMMENT 'Fecha de mandamiento de firma. Relacionado con el estado de la pipeline.  [[17774]]'
    ,des_fecacce COMMENT 'Fecha de oportunidad de negocio aceptada. Relacionado con el estado de la pipeline.  [[17775]]'
    ,des_fecmiss COMMENT 'Fecha de oportunidad de negocio fallada o perdida. Relacionado con el estado de la pipeline.  [[17776]]'
    ,des_mainreas COMMENT 'Descripcion de la razon de rechazo del acuerdo.  [[17753]]'
    ,des_reasonmi COMMENT 'Descripcion larga del motivo de rechazo del acuerdo. Relacionado con el estado de la pipeline.'
    ,des_exsystem COMMENT 'Descripcion del sistema donde se ejecuta la pipeline.'
    ,des_idtrade COMMENT 'Codigo de Transacion en los sitemas origenes Ejemplos:- Murex Numbers: 7075591 - 7075536 - 7075523- Canales ElectronicosVA[[18141]]'
    ,des_qnupodc COMMENT 'Ingresos potenciales pipeline, segun moneda.  [[17779]]'
    ,cod_dealcurr COMMENT 'Moneda de acuerdo al ingreso potencial pipeline.  [[12892]]'
    ,des_qnupocu COMMENT 'Ingresos potenciales pipeline en la moneda de acuerdo actual.  [[17780]]'
    ,des_porprob COMMENT 'Probabilidad de exito de la pipeline.  [[17781]]'
    ,des_qnuredc COMMENT 'Ingresos esperados por pipeline, en moneda segtecn acuerdo.  [[17777]]'
    ,des_qnurerc COMMENT 'Ingresos esperados por pipeline, en moneda actual.  [[17778]]'
    ,des_fecestm COMMENT 'Fecha estimada del cierre de pipeline.'
    ,des_fecdele COMMENT 'Fecha de borrado de la pipeline.'
    ,cod_pipconfi COMMENT 'Codigo Descripcion confidencial que Yes/No que indica si la Pipeline es confidencial.'
    ,des_pipeurl COMMENT 'Url generada para redirigir al detalle de la pipeline. Autentificacion SSO [[18088]]'
    ,des_updefesf COMMENT 'Del total de honorarios por adelantado que se pagaran, las que serA diferidas a loa largo de la vida del contrato. VA [[20282]]'
    ,des_notdefsf COMMENT 'Del total de honorarios por adelantado que se pagaran, las que NO serAn diferidas a lo largo de la vida del contrato. VA [[20283]]'
    ,des_fihodcsf COMMENT 'Final Hold que el Banco tendrA . En caso de que no hay ninguna suscripcion, Hold final serA el mismo que el compromiso del Banco. VA [[20284]]'
    ,des_fihorcsf COMMENT 'Final Hold que el Banco tendrA . En caso de que no hay ninguna suscripcion, Final Hold serA el mismo que el compromiso del Banco. Contravalorado a EUR. VA [[20285]]'
    ,des_adcodcsf COMMENT 'Honorarios de asesoramiento / de coordinacion que se cobrarAn a la operacion. VA [[20286]]'
    ,des_adcorcsf COMMENT 'Honorarios de asesoramiento / de coordinacion que se cobrarAn a la operacion. En EUR. VA [[20287]]'
    ,des_atandcsf COMMENT 'Agencia y otras cuotas que se cobrarAn a la operacion. En DIVISA. VA [[20288]]'
    ,des_atanrcsf COMMENT 'Agencia y otras cuotas que se cobrarAn a la operacion. En EUR. VA [[20289]]'
    ,des_poredcsf COMMENT 'Suma de los mArgenes y comisiones ingresos esperados de los primeros 12 meses de la operacion (cAlculo implicito). En DIVISA. VA [[20290]]'
    ,des_porercsf COMMENT 'Suma de los mArgenes y comisiones ingresos esperados de los primeros 12 meses de la operacion (cAlculo implicito). En EURO. VA [[20291]]'
    ,des_pomadcsf COMMENT 'Los ingresos del mArgen esperado de los primeros 12 meses de la operacion (cAlculo implicito ). En DIVISA. VA [[20292]]'
    ,des_pomarcsf COMMENT 'Los ingresos del mArgen esperado de los primeros 12 meses de la operacion (cAlculo implicito ). En EURO. VA [[20293]]'
    ,des_pofedcsf COMMENT 'Son los Ingresos por comisiones previstos de los primeros 12 meses de la operacion (cAlculo implicito ). En DIVISA. VA [[20294]]'
    ,des_pofercsf COMMENT 'Son los Ingresos por comisiones previstos de los primeros 12 meses de la operacion (cAlculo implicito ). En EURO. VA [[20295]]'
    ,des_todedcsf COMMENT 'Tamaño total de la deuda. En DIVISA. VA [[20296]]'
    ,des_todercsf COMMENT 'Tamaño total de la deuda. En EURO. VA [[20297]]'
    ,cod_prodtysf COMMENT 'Se refiere a los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-SF: 1 Advisory 2 Asset Finance 3 Leveraged 4 Project 6 Other. VA [[203'
    ,des_protypsf COMMENT 'Se refiere a los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-SF: 1 Advisory 2 Asset Finance 3 Leveraged 4 Project 6 Other. [[20345]'
    ,cod_tprojesf COMMENT 'Se refiere a los diferentes tipos de proyectos que existen dentro cada clase de Producto de nivel II. Por ejmpo para S&SL-SF: 1 Acquisition 2 Brownfield 5 Greenfield 6 Refinancing 7 Restructuring. VA'
    ,des_typrojsf COMMENT 'Se refiere a los diferentes tipos de proyectos que existen dentro cada clase de Producto de nivel II. Por ejmpo para S&SL-SF: 1 Acquisition 2 Brownfield 5 Greenfield 6 Refinancing 7 Restructuring [[20'
    ,cod_sbprodsf COMMENT 'Se refiere a los diferentes subproductos aplicables a cada tipo de producto : 1 Acquisit. Finan. 2 Aviation 3 Rolling Stock 4 Listed Shares 5 Other Asset Finance 8 Energy - Oil & Gas 9 Environment 11'
    ,des_subprosf COMMENT 'Se refiere a los diferentes subproductos aplicables a cada tipo de producto : 1 Acquisit. Finan. 2 Aviation 3 Rolling Stock 4 Listed Shares 5 Other Asset Finance 8 Energy - Oil & Gas 9 Environment 11'
    ,des_boropnsf COMMENT 'Prestatario o nombre de la operacion para su identificacion. [[20360]]'
    ,cod_dstatusf COMMENT 'Es el estado de acuerdo y sus valores va en funcion de la fase de negociacion del acuerdo: 1 RFP Received  2 Indicative offer  3 Due diligence  4 Binding offer  5 Documentation phase  6 Syndication'
    ,des_delstasf COMMENT 'Es la Descripcion del estado de acuerdo y sus valores va en funcion de la fase de negociacion del acuerdo: 1 RFP Received  2 Indicative offer  3 Due diligence  4 Binding offer  5 Documentation phas'
    ,cod_ascounsf COMMENT 'Se refiere a los paises donde el asset estA localizado. [[20362]]'
    ,des_ascounsf COMMENT 'Se refiere a la descricpcion de los paises donde el asset estA localizado. [[20362]]'
    ,cod_bvarolsf COMMENT 'Se refiere a los diferentes roles que BBVA puede tener en la Operacion: 1 Agent 2 Advisor 3Bookrunner 4Coordinator 5MLA 6Participant 7Bilateral 8if other, specify VA [[20363]]'
    ,des_bvrolesf COMMENT 'Se refiere a las descripciones de los diferentes roles que BBVA puede tener en la Operacion: 1Agent 2Advisor 3Bookrunner 4Coordinator 5MLA 6Participant 7Bilateral 8if other, specify [[20363]]'
    ,cod_astgeosf COMMENT 'Se refiere a la geografia donde se encuentra el Asset. [[20364]]'
    ,des_astgeosf COMMENT 'Se refiere a la geografia donde se encuentra el Asset. [[20364]]'
    ,des_desidcsf COMMENT 'Valor total de la operacion / empresa. En DIVISA. VA [[20298]]'
    ,des_desircsf COMMENT 'Valor total de la operacion / empresa. En EURO. VA [[20299]]'
    ,des_bbvadcsf COMMENT 'ComprometidoTotal del Banco. En DIVISA. VA [[20300]]'
    ,des_bbvarcsf COMMENT 'ComprometidoTotal del Banco. En EURO. VA [[20301]]'
    ,des_avexdcsf COMMENT 'Importe total esperado que se librarA en los primeros 12 meses despues de la firma del acuerdo. En DIVISA. VA [[20302]]'
    ,des_avexrcsf COMMENT 'Importe total esperado que se librarA en los primeros 12 meses despues de la firma del acuerdo. En EUROS. VA [[20303]]'
    ,des_tenorysf COMMENT 'Vida contractual total de la operacion por contrato. VA [[20304]]'
    ,des_avlifysf COMMENT 'Media ponderada de los años hasta que la oferta estA completamente pagada ( ponderado por los reembolsos ). VA [[20305]]'
    ,des_contensf COMMENT 'In case the deal is part of a greenfield project, it refers to the total years until the end of the construction period. VA [[20306]]'
    ,des_relcomsf COMMENT 'Texto de entrada libre de Comentarios relevantes [[20318]]'
    ,des_chanstsf COMMENT 'Fecha de cambio de Estado. VA [[20319]]'
    ,des_grosprsf COMMENT 'Spread bruto que se cobrarA al acuerdo. VA [[20307]]'
    ,des_cudelsf COMMENT 'Coste aplicable al acuerdo de financiacion . En caso de que no se conozca, se realiza la mejor suposicion de el. VA [[20308]]'
    ,des_comfeesf COMMENT 'Comision de compromiso que se cobrarA al acuerdo. VA [[20309]]'
    ,des_allinsf COMMENT 'Importe Total del Acuerdo (calculo implicito) VA [[20310]]'
    ,des_rarexpsf COMMENT 'RaR esperado Antes del Coste de Financiacion . En caso de que la oportunidad de negocio se encuentre en una etapa temprana y el RaR no se sepa , se realiza r su mejor suposicion . VA [[20311]]'
    ,des_rarexssf COMMENT 'RaR esperado Despues del Coste de Financiacion . En caso de que la oportunidad de negocio se encuentre en una etapa temprana y el RaR no se sepa , se realiza r su mejor suposicion . VA [[20312]]'
    ,des_delgspsf COMMENT 'En caso de una refinanciacion ( un acuerdo donde participo el Banco) o acuerdo de Reestructuracion , es la propagacion bruto aplicable anterior. VA [[20313]]'
    ,des_upffedsf COMMENT 'Comisiones a cobrar up front. En DIVISA. VA [[20314]]'
    ,des_upffeesf COMMENT 'Comisiones a cobrar up front. En EURO. VA [[20315]]'
    ,des_ptfesdsf COMMENT 'Total de comisiones potenciales. En DIVISA. VA [[20365]]'
    ,des_ptfesesf COMMENT 'Total de comisiones potenciales. En EURO. VA [[20366]]'
    ,des_updefcsl COMMENT 'Del total de honorarios por adelantado que se pagaran, las que serA diferidas a lo largo de la vida del contrato. VA [[20282]]'
    ,des_notdecsl COMMENT 'Del total de honorarios por adelantado que se pagaran, las que NO serAn diferidas a lo largo de la vida del contrato. VA [[20283]]'
    ,des_agfedcsl COMMENT 'Agencia y otras cuotas que se cobrarAn a la operacion. En DIVISA. VA [[20288]]'
    ,des_agfercsl COMMENT 'Agencia y otras cuotas que se cobrarAn a la operacion. En EUR. VA [[20289]]'
    ,des_poredcsl COMMENT 'Suma de los mArgenes y comisiones ingresos esperados de los primeros 12 meses de la operacion (cAlculo implicito). En DIVISA. VA [[20290]]'
    ,des_porercsl COMMENT 'Suma de los mArgenes y comisiones ingresos esperados de los primeros 12 meses de la operacion (cAlculo implicito). En EURO. VA [[20291]]'
    ,des_pomadcsl COMMENT 'Los ingresos del mArgen esperado de los primeros 12 meses de la operacion (cAlculo implicito ). En DIVISA. VA [[20292]]'
    ,des_pomarcsl COMMENT 'Los ingresos del mArgen esperado de los primeros 12 meses de la operacion (cAlculo implicito ). En EURO. VA [[20293]]'
    ,des_pofedcsl COMMENT 'Son los Ingresos por comisiones previstos de los primeros 12 meses de la operacion (cAlculo implicito ). En DIVISA. VA [[20294]]'
    ,des_pofercsl COMMENT 'Son los Ingresos por comisiones previstos de los primeros 12 meses de la operacion (cAlculo implicito ). En EUROS. VA [[20295]]'
    ,des_cofedcsl COMMENT 'Comisiones de coordinacion. En DIVISA. VA [[20367]]'
    ,des_cofercsl COMMENT 'Comisiones de coordinacion. En EURO. VA [[20368]]'
    ,des_adfedcsl COMMENT 'Comisiones de asesoramiento.En DIVISA. VA [[20369]]'
    ,des_adfercsl COMMENT 'Comisiones de asesoramiento. En EURO. VA [[20370]]'
    ,cod_prposcsl COMMENT 'Se refiere a la finalidad de la financiacion. La instalacion de base de prestamos se refiere por lo general a los financiamientos de las empresas de petroleo y gas. 1        Acquisition Finance 2'
    ,des_purpocsl COMMENT 'Se refiere a la finalidad de la financiacion. La instalacion de base de prestamos se refiere por lo general a los financiamientos de las empresas de petroleo y gas. 1        Acquisition Finance 2'
    ,cod_typedcsl COMMENT 'Se refiere al tipo de financiacion : bilateral o sindicado .  1        Bilateral - Accordion Execution 2        Syndicated - Accordion Execution 3        Advisory 4        Bilateral - Amendment / Wa'
    ,des_typdecsl COMMENT 'Se refiere al tipo de financiacion : bilateral o sindicado .  1        Bilateral - Accordion Execution 2        Syndicated - Accordion Execution 3        Advisory 4        Bilateral - Amendment / Wa'
    ,cod_numtrcsl COMMENT 'Numero de secciones/particiones de las que se compone la pipeline. VA [[20373]]'
    ,cod_bbvarcsl COMMENT 'Se refiere a los diferentes roles que BBVA puede tener en la Operacion: 1        Agent 2        Advisor 3        Bookrunner 4        Coordinator 5        MLA 6        Participant 7        Bilateral'
    ,des_bbvarcsl COMMENT 'Se refiere a los diferentes roles que BBVA puede tener en la Operacion: 1        Agent 2        Advisor 3        Bookrunner 4        Coordinator 5        MLA 6        Participant 7        Bilateral'
    ,cod_roluscsl COMMENT 'Se refiere a los diferentes roles que BBVA puede tener en la Operacion: 1        Sole Lead Arranger 2        Joint Lead Arranger 3        Administrative Agent 4        Documentation Agent 5        S'
    ,des_roluscsl COMMENT 'Se refiere a los diferentes roles que BBVA puede tener en la Operacion: 1        Sole Lead Arranger 2        Joint Lead Arranger 3        Administrative Agent 4        Documentation Agent 5        S'
    ,cod_origecsl COMMENT 'Se refiere al equipo geografico  que estA estructurando la transaccion. VA [[20374]]'
    ,des_orgeocsl COMMENT 'Se refiere al equipo geografico  que estA estructurando la transaccion. [[20374]]'
    ,des_gloadcsl COMMENT 'Cantidad acuerdo global. En DIVISA. VA [[20341]]'
    ,des_gloarcsl COMMENT 'Cantidad acuerdo global. En EUROS. VA [[20342]]'
    ,des_unwrdcsl COMMENT 'Importe asegurado. En DIVISA. VA [[20343]]'
    ,des_unwrrcsl COMMENT 'Importe asegurado. En EUROS. VA [[20344]]'
    ,cod_dstatcsl COMMENT 'Es el estado de acuerdo y sus valores va en funcion de la fase de negociacion del acuerdo.  1 RFP Received 2 Indicative offer 3 Due diligence 4 Binding offer 5 Documentation phase 6 Syndication pha'
    ,des_dstatcsl COMMENT 'Es el estado de acuerdo y sus valores va en funcion de la fase de negociacion del acuerdo.  1 RFP Received 2 Indicative offer 3 Due diligence 4 Binding offer 5 Documentation phase 6 Syndication pha'
    ,des_relcocsl COMMENT 'Texto de entrada libre de Comentarios relevantes [[20318]]'
    ,des_chastcsl COMMENT 'Fecha de cambio de Estado. VA [[20319]]'
    ,des_cosfucsl COMMENT 'Coste aplicable al acuerdo de financiacion . En caso de que no se conozca, se realiza la mejor suposicion de el. VA [[20308]]'
    ,des_roecocsl COMMENT 'Rentabilidad financiera o ROE VA [[20346]]'
    ,des_totfecsl COMMENT 'Falta deficion por parte del usuario. VA [[20347]]'
    ,des_avrtocsl COMMENT 'Media ponderada de los meses. VA [[20320]]'
    ,des_waifdcsl COMMENT 'Tarifa de renuncia en DIVISA. VA [[20321]]'
    ,des_waifrcsl COMMENT 'Tarifa de renuncia en EUROS [[20322]]'
    ,des_alindcsl COMMENT 'Puntos bAsicos para el total dispuesto. VA [[20375]]'
    ,des_alundcsl COMMENT 'Puntos bAsicos para el total NO dispuesto. VA [[20376]]'
    ,des_rexbfcsl COMMENT 'RaR esperado Antes del Coste de Financiacion . En caso de que la oportunidad de negocio se encuentre en una etapa temprana y el RaR no se sepa , se realiza r su mejor suposicion . VA [[20311]]'
    ,des_rexpocsl COMMENT 'RaR esperado Despues del Coste de Financiacion . En caso de que la oportunidad de negocio se encuentre en una etapa temprana y el RaR no se sepa , se realiza r su mejor suposicion . VA [[20312]]'
    ,des_prifdcsl COMMENT 'En caso de refinanciacion de una instalacion, la tecltima toma actual de las instalaciones existentes. En DIVISA. VA [[20323]]'
    ,des_prifrcsl COMMENT 'En caso de refinanciacion de una instalacion, la tecltima toma actual de las instalaciones existentes. En EUROS. VA [[20324]]'
    ,des_prdgscsl COMMENT 'En caso de una refinanciacion ( un acuerdo donde participo el Banco) o acuerdo de Reestructuracion , es la propagacion bruto aplicable anterior. VA [[20313]]'
    ,des_pdcogcsl COMMENT 'En caso de refinanciacion de un compromiso instalaciones la cuota/garantia previa de las instalaciones existentes. VA [[20325]]'
    ,des_pdnescsl COMMENT 'En caso de refinanciacion de una instalacion de red tendida existente de la instalacion ( tener en cuenta el costo de la financiacion podria haber cambiado ) VA [[20326]]'
    ,cod_protystf COMMENT 'Se refiere a los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-STF: 1STF ECA 2STF Asset-Backed VA [[20345]]'
    ,des_protystf COMMENT 'Se refiere a los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-SF: Se refiere a los diferentes tipos de productos que existen, para c'
    ,des_abvadstf COMMENT 'Importe Final BBVA. En DIVISA. VA [[20237]]'
    ,des_abvarstf COMMENT 'Importe Final BBVA. En EUROS. VA [[20328]]'
    ,cod_totfastf COMMENT 'Codigo de la Divisa en las que viene el importe para el Producto GTB-STF [[20383]]'
    ,des_totfastf COMMENT 'Listado de las modenas, Divsas en las que viene el importe [[20377]]'
    ,des_tofadstf COMMENT 'Cantidad de credito para financiar el proyecto. En DIVISA. VA [[20239]]'
    ,des_tofarstf COMMENT 'Cantidad de credito para financiar el proyecto. En EUROS. VA [[20330]]'
    ,des_tofedstf COMMENT 'Importe Total planeado cobrar por honorarios totales. DIVISA. VA [[20378]]'
    ,des_toferstf COMMENT 'Importe Total planeado cobrar por honorarios totales. En EURO. VA [[20379]]'
    ,des_tomadstf COMMENT 'Importe planificado cobrar por el margen total. En DIVISA. VA [[20331]]'
    ,des_tomarstf COMMENT 'Importe planificado cobrar por el margen total. En EURO. VA [[20332]]'
    ,des_totinstf COMMENT 'Campo automAtico , Honorarios totales + Margen total. VA [[20380]]'
    ,des_toinrstf COMMENT 'STF - Total Income (Report Currency) [[20380]]'
    ,des_dwpemstf COMMENT 'Duracion en meses del periodo de disponibilidad del credito. VA [[20333]]'
    ,des_rpermstf COMMENT 'Duracion en meses del plazo de amortizacion del credito. VA [[20334]]'
    ,des_netspstf COMMENT 'Spread Neto, campo calculado: Gross Spread - Cost of Funding. VA [[20335]]'
    ,cod_prty3stf COMMENT 'Se refiere a los diferentes tipos de productos de nivel  que existen dentro de STF ( o las clases de Productos que apliquen). Por ejemplo para la clase de Producto GTB-STF 1        Buyers Credit 2'
    ,des_prty3stf COMMENT 'Se refiere a los diferentes tipos de productos de nivel  que existen dentro de STF ( o las clases de Productos que apliquen). Por ejemplo para la clase de Producto GTB-STF 1        Buyers Credit 2'
    ,cod_manofstf COMMENT 'Codigo de oficina donde se origino la transaccion. EJ: STF BANCOMER, STF COLOMBIA, STF COMPASS, STF FRANCE, STF GERMANY,... [[20681]]'
    ,des_manofstf COMMENT 'Descripcion de la oficina donde se origino la transaccion. [[20681]]'
    ,cod_accofstf COMMENT 'Condigo de la oficina en la que se tiene en cuenta el activo. EJ: STF BANCOMER, STF COLOMBIA, STF USA Compass, STF FRANCE, STF GERMANY,... [[20682]]'
    ,des_accofstf COMMENT 'Descripcion de la Oficina en la que se tiene en cuenta el activo. [[20682]]'
    ,cod_riscostf COMMENT 'Condigo Pais de prestatario. EJ: ABU DHABI, ANDORRA, UNITED ARAB EMIRATES, AFGHANISTAN, ANTIGUA AND BARBUDA,... [[20683]]'
    ,des_riscostf COMMENT 'Descripcion del pais de prestatario. [[20683]]'
    ,des_expofstf COMMENT 'Descripcion de la oficina de Contabilidad. [[20684]]'
    ,cod_clirostf COMMENT 'Codigo de diferentes roles del cliente. EJ: 1Exporter 2Importer 3Bank [[20685]]'
    ,des_clirostf COMMENT 'Descripcion de los diferentes roles del cliente. [[20685]]'
    ,des_conamstf COMMENT 'Nombre de Contrapartida del acuerdo. [[20686]]'
    ,cod_bvarostf COMMENT 'Codigo de los diferentes roles que BBVA puede tener en la Operacion: 1Agent 2Advisor 3Bookrunner 4Coordinator 5MLA 6Participant 7Bilateral 8if other, specify [[20363]]'
    ,des_bvarostf COMMENT 'Descripcion de los diferentes roles que BBVA puede tener en la Operacion: 1Agent 2Advisor 3Bookrunner 4Coordinator 5MLA 6Participant 7Bilateral 8if other, specify [[20363]]'
    ,des_posfustf COMMENT 'Descripcion del RaR esperado Despues del Coste de Financiacion . En caso de que la oportunidad de negocio se encuentre en una etapa temprana y el RaR no se sepa , se realiza r su mejor suposicion .'
    ,cod_cosegstf COMMENT 'Condigo de segmentos diferentes que existen para las contrapartidas. EJ: 1INSTITUTIONAL CLIENT 2PUBLIC SECTOR 3SME & RETAIL 4OTHERS 5CORPORATE .... [[20687]]'
    ,des_cosegstf COMMENT 'Descripcion de los diferentes segmentos que existen para las contrapartidas. [[20687]]'
    ,cod_cocoustf COMMENT 'Condigo Paises diferentes que existen para las contrapartidas. EJ: 1INSTITUTIONAL CLIENT 2PUBLIC SECTOR 3SME & RETAIL 4OTHERS 5CORPORATE 6FINANCIAL SPONSORS [[20688]]'
    ,des_cocoustf COMMENT 'Descripcion de los diferentes paises que existen para las contrapartidas. [[20688]]'
    ,cod_factystf COMMENT 'Condigo para diferentes tipos de instalaciones que existe para los productos STF. EJ: 1Supply 2Turnkey 3Not Applicable [[20689]]'
    ,des_factystf COMMENT 'Descripcion de los diferentes tipos de instalaciones que existe para los productos STF. [[20689]]'
    ,des_buyerstf COMMENT 'Nombre del comprador (vacio si la transaccion no tiene comprador). [[20690]]'
    ,des_repodstf COMMENT 'Resto de la cantidad de credito financiado por el ClubDeal. En DIVISA. [[20691]]'
    ,des_reporstf COMMENT 'Resto de la cantidad de credito financiado por el ClubDeal. En EUR. [[20691]]'
    ,cod_tyintstf COMMENT 'Codigo para diferentes tipos de interes aplicados al sueldo bruto. EJ: 1Fixed 2Variable 3Special [[20692]]'
    ,des_tyintstf COMMENT 'Descripcion de los diferentes tipos de interes aplicados al sueldo bruto. [[20692]]'
    ,des_ratbostf COMMENT 'Descripcion de la calificacion de prestatario. [[20693]]'
    ,des_creagstf COMMENT 'Fecha de la firma del credito. [[20694]]'
    ,des_ofmatstf COMMENT 'Oferta de madurez BBVA. [[20695]]'
    ,des_grospstf COMMENT 'Spread bruto que se cobrarA al acuerdo. [[20307]]'
    ,des_cosfustf COMMENT 'Coste aplicable al acuerdo de financiacion . En caso de que no se conozca, se realiza la mejor suposicion de el. [[20308]]'
    ,des_upfeestf COMMENT 'Comisiones a cobrar up front. [[20314]]'
    ,des_comfestf COMMENT 'Comision de compromiso que se cobrarA al acuerdo. [[20309]]'
    ,des_guarastf COMMENT 'Nombre del fiador del credito. [[20696]]'
    ,des_ratgustf COMMENT 'Descripcion de la calificacion del fiador. [[20697]]'
    ,cod_ecanastf COMMENT 'Condigo ECA (vacio si la transaccion no tiene ECA). [[20698]]'
    ,des_ecanastf COMMENT 'Nombre ECA (vacio si la transaccion no tiene ECA). [[20698]]'
    ,des_ecacostf COMMENT 'Porcentaje de cobertura ECA (vacio si la transaccion no tiene ECA). [[20699]]'
    ,des_maecastf COMMENT 'Dia de expiracion de la cobertura ECA. [[20700]]'
    ,cod_caristf COMMENT 'En caso de que el acuerdo tenga riesgo de tipo de interes de cobertura CARI. EJ: 1Yes 2No [[20701]]'
    ,des_caristf COMMENT 'En caso de que el acuerdo tenga riesgo, Descripcion del tipo de interes de cobertura CARI. [[20701]]'
    ,des_carmastf COMMENT 'Fecha de expiracion de la oferta del tipo de interes. [[20702]]'
    ,des_relevstf COMMENT 'Descripcion de transacciones sobre algtecn punto de relevancia. [[20703]]'
    ,des_agfeestf COMMENT 'Decripcion de agencia y otras cuotas que se cobrarAn a la operacion. [[20288]]'
    ,des_othfestf COMMENT 'Descripcion de otras cuotas que se cobrarAn a la operacion. [[20288]]'
    ,des_yefedstf COMMENT 'Importe a cobrar por honorarios en el año actual. EN DIVISA [[20704]]'
    ,des_yeferstf COMMENT 'Importe a cobrar por honorarios en el año actual. EN EUR [[20704]]'
    ,des_yemadstf COMMENT 'Importe a cobrar por el margen en el año actual. EN DIVISA. [[20705]]'
    ,des_yemarstf COMMENT 'Importe a cobrar por el margen en el año actual. EN EUR. [[20705]]'
    ,des_yeindstf COMMENT 'Importe a cobrar por el ingreso en el año actual. EN DIVISA. [[20706]]'
    ,des_yeinrstf COMMENT 'Importe a cobrar por el ingreso en el año actual. EN EUR. [[20706]]'
    ,cod_funenstf COMMENT 'Condigo tipos de entidades de financiacion. EJ: 1BBVA SA 2BBVA Other 3External 4Unfunded [[20707]]'
    ,des_funenstf COMMENT 'Descripcion de los diferentes tipos de entidades de financiacion. [[20707]]'
    ,des_racnnstf COMMENT 'Fecha de aprobacion del riesgo - CNN. [[20708]]'
    ,des_ragrcstf COMMENT 'Fecha de aprobacion del riesgo - GRC. [[20709]]'
    ,cod_rousastf COMMENT 'Descripcion de los diferentes roles que BBVA puede tener en la Operacion: 1        Sole Lead Arranger 2        Joint Lead Arranger 3        Administrative Agent 4        Documentation Agent 5'
    ,des_rousastf COMMENT 'Descripcion de los diferentes roles que BBVA puede tener en la Operacion: 1        Sole Lead Arranger 2        Joint Lead Arranger 3        Administrative Agent 4        Documentation Agent 5'
    ,cod_prtypttf COMMENT 'Se refiere a los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-TTF: 1TF import/export 2TF forfaiting 3TF avales 4TF L/C 5Other T'
    ,des_prtypttf COMMENT 'Se refiere a los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-TTF: 1TF import/export 2TF forfaiting 3TF avales 4TF L/C 5Other T'
    ,des_abvadttf COMMENT 'Importe Final BBVA. En DIVISA. VA [[20237]]'
    ,des_abvarttf COMMENT 'Importe Final BBVA. En EUROS. VA [[20328]]'
    ,des_netspttf COMMENT 'Spread Neto, campo calculado: Gross Spread - Cost of Funding. VA [[20335]]'
    ,cod_prty3ttf COMMENT 'Se refiere a los diferentes tipos de productos de nivel  que existen dentro de TTF ( o las clases de Productos que apliquen). Por ejemplo para la clase de Producto GTB-TTF 1L/C Confirmation 2L/C Si'
    ,des_prty3ttf COMMENT 'Se refiere a los diferentes tipos de productos de nivel  que existen dentro de TTF ( o las clases de Productos que apliquen). Por ejemplo para la clase de Producto GTB-TTF 1L/C Confirmation 2L/C Si'
    ,des_tenmottf COMMENT 'Vida contractual total de la operacion por contrato. VA [[20304]]'
    ,des_rfpttf COMMENT 'En el caso del acuerdo es la solicitud de propuesta(Request For Proposal).  Campo de texto que indica Si/No. VA [[20382]]'
    ,cod_courittf COMMENT 'Codigo del Pais del prestatario. EJ: ABABU DHABI ADANDORRA AEUNITED ARAB EMIRATES AFAFGHANISTAN AGANTIGUA AND BARBUDA [[20683]]'
    ,des_courittf COMMENT 'Descripcion de pais de prestatario. [[20683]]'
    ,des_arfedttf COMMENT 'Cantidad que el banco va a ganar por comisiones de apertura. EN DIVISA. [[20710]]'
    ,des_arferttf COMMENT 'Cantidad que el banco va a ganar por comisiones de apertura. EN EUR. [[20710]]'
    ,des_anridttf COMMENT 'Tasa de riesgo anual que ganarA el banco. EN DIVISA. [[20711]]'
    ,des_riferttf COMMENT 'Tasa de riesgo anual que ganarA el banco. EN EUR. [[20711]]'
    ,des_cofedttf COMMENT 'Comision de compromiso que se cobrarA al acuerdo.EN DIVISA. [[20309]]'
    ,des_coferttf COMMENT 'Comision de compromiso que se cobrarA al acuerdo. EN EUR. [[20309]]'
    ,des_grospttf COMMENT 'Spread bruto que se cobrarA al acuerdo. [[20307]]'
    ,des_anfedttf COMMENT 'Las tasas anuales que gana el banco. EN DIVISA. [[20678]]'
    ,des_anferttf COMMENT 'Las tasas anuales que gana el banco. EN EUR. [[20678]]'
    ,des_selerttf COMMENT 'Nombre del vendedor (vacio si no hay transaccion). [[20713]]'
    ,des_drapettf COMMENT 'Duracion del periodo de reduccion de credito. [[20714]]'
    ,des_cosfuttf COMMENT 'Coste aplicable al acuerdo de financiacion . En caso de que no se conozca, se realiza la mejor suposicion de el. [[20308]]'
    ,cod_clirottf COMMENT 'Codigo de los diferentes roles del cliente. EJ: 1Exporter 2Importer 3Bank [[20685]]'
    ,des_clirottf COMMENT 'Descripcion de los diferentes roles del cliente. [[20685]]'
    ,des_counattf COMMENT 'Nombre de Contrapartida del acuerdo. [[20686]]'
    ,cod_cousettf COMMENT 'Codigo de los segmentos diferentes que existen para las contrapartidas. EJ: 1INSTITUTIONAL CLIENT 2PUBLIC SECTOR 3SME & RETAIL 4OTHERS 5CORPORATE 6FINANCIAL SPONSORS [[20687]]'
    ,des_cousettf COMMENT 'Segmentos diferentes que existen para las contrapartidas. [[20687]]'
    ,cod_coucottf COMMENT 'Codigo del pais existente para las contrapartidas. EJ: ABABU DHABI ADANDORRA AEUNITED ARAB EMIRATES AFAFGHANISTAN AGANTIGUA AND BARBUDA AIANGUILLA ... [[20688]]'
    ,des_coucottf COMMENT 'Descripcion de los diferentes paises que existen para las contrapartidas. [[20688]]'
    ,cod_bvaclttf COMMENT 'Es cliente BBVA o no?. EJ: 1Yes 2No [[20712]]'
    ,des_bvaclttf COMMENT 'Es cliente BBVA o no?. [[20712]]'
    ,des_baimdttf COMMENT 'Nombre de los bancos implicados en el acuerdo. [[20716]]'
    ,cod_protypcm COMMENT 'Se refiere a los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-CM: 1Electronic channels 2Cards 3Collections 4Forfaits - other fee'
    ,des_protypcm COMMENT 'Se refiere a los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-CM: 1Electronic channels 2Cards 3Collections 4Forfaits - other fee'
    ,des_ambvadcm COMMENT 'Importe Final BBVA. En DIVISA. VA [[20237]]'
    ,des_ambvarcm COMMENT 'Importe Final BBVA. En EUROS. VA [[20328]]'
    ,des_netsprcm COMMENT 'Spread Neto, campo calculado: Gross Spread - Cost of Funding. VA [[20335]]'
    ,des_rfpcm COMMENT 'En el caso del acuerdo es la solicitud de propuesta(Request For Proposal). VA [[20382]]'
    ,des_avabadcm COMMENT 'Saldo Medio anual, referido al saldo medio dirigido. En DIVISA. VA [[20337]]'
    ,des_avabarcm COMMENT 'Saldo Medio anual, referido al saldo medio dirigido. En EUROS. VA [[20338]]'
    ,des_grosprcm COMMENT 'Spread bruto que se cobrarA al acuerdo. [[20307]]'
    ,des_anufedcm COMMENT 'Las tasas anuales que gana el banco. EN DIVISA. [[20678]]'
    ,des_anufercm COMMENT 'Las tasas anuales que gana el banco. EN EUR. [[20678]]'
    ,des_implemcm COMMENT 'Fecha de implementacion de la solucion tecnologica. [[20679]]'
    ,des_cosfuncm COMMENT 'Coste aplicable al acuerdo de financiacion . En caso de que no se conozca, se realiza la mejor suposicion de el. [[20308]]'
    ,cod_protypwk COMMENT 'Se refiere a los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-WK: 1Receivables 2Confirming 3Credit Accounts 4Factoring 5Fx 6TB'
    ,des_protypwk COMMENT 'Se refiere a los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-WK: 1Receivables 2Confirming 3Credit Accounts 4Factoring 5Fx 6TB'
    ,des_ambvadwk COMMENT 'Importe Final BBVA. En DIVISA. VA [[20237]]'
    ,des_ambvarwk COMMENT 'Importe Final BBVA. En EUROS. VA [[20328]]'
    ,des_netsprwk COMMENT 'Spread Neto, campo calculado: Gross Spread - Cost of Funding. VA [[20335]]'
    ,des_tenomowk COMMENT 'Vida contractual total de la operacion por contrato. VA [[20304]]'
    ,des_rfpwk COMMENT 'En el caso del acuerdo es la solicitud de propuesta(Request For Proposal).  Campo de texto que indica Si/No. VA [[20382]]'
    ,des_avabadwk COMMENT 'Saldo Medio anual, referido al saldo medio dirigido. En DIVISA. VA [[20337]]'
    ,des_avabarwk COMMENT 'Saldo Medio anual, referido al saldo medio dirigido. En EUROS. VA [[20338]]'
    ,des_receidwk COMMENT 'Importe promedio de los creditos. En divisa. [[20715]]'
    ,des_receirwk COMMENT 'Importe promedio de los creditos. En EUR [[20715]]'
    ,des_opbaldwk COMMENT 'Apertura Saldo Promedio Cuenta. EN DIVISA. [[20717]]'
    ,des_opbalrwk COMMENT 'Apertura Saldo Promedio Cuenta. EN EUR. [[20717]]'
    ,des_nurecewk COMMENT 'Ntecmero de creditos anuales. [[20718]]'
    ,des_arrfedwk COMMENT 'Cantidad que el banco va a ganar por comisiones de apertura. EN DIVISA. [[20710]]'
    ,des_arrferwk COMMENT 'Cantidad que el banco va a ganar por comisiones de apertura. EN EUR. [[20710]]'
    ,des_risfedwk COMMENT 'Tasa de riesgo anual que ganarA el banco. EN DIVISA. [[20711]]'
    ,des_risferwk COMMENT 'Tasa de riesgo anual que ganarA el banco. EN EUR. [[20711]]'
    ,des_comfedwk COMMENT 'Comision de compromiso que se cobrarA al acuerdo. EN DIVISA. [[20309]]'
    ,des_comferwk COMMENT 'Comision de compromiso que se cobrarA al acuerdo. EN EUR. [[20309]]'
    ,des_disfedwk COMMENT 'Honorarios de la disposicion que ganarA el banco. EN DIVISA. [[20719]]'
    ,des_disferwk COMMENT 'Honorarios de la disposicion que ganarA el banco. [[20719]]'
    ,des_grosprwk COMMENT 'Spread bruto que se cobrarA al acuerdo. [[20307]]'
    ,des_anfeedwk COMMENT 'Las tasas anuales que gana el banco. EN DIVISA. [[20678]]'
    ,des_anfeerwk COMMENT 'Las tasas anuales que gana el banco. EN EUR. [[20678]]'
    ,des_cosfunwk COMMENT 'Coste aplicable al acuerdo de financiacion . En caso de que no se conozca, se realiza la mejor suposicion de el. [[20308]]'
    ,cod_protypcr COMMENT 'Se refiere a los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-CR: 1Accounts 2Time Deposit 4Euro-deposits 5Puttable deposits 6Ce'
    ,des_protypcr COMMENT 'Se refiere a los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-CR: 1Accounts 2Time Deposit 4Euro-deposits 5Puttable deposits 6Ce'
    ,des_ambvadcr COMMENT 'Importe Final BBVA. En DIVISA. VA [[20237]]'
    ,des_ambvarcr COMMENT 'Importe Final BBVA. En EUROS. VA [[20328]]'
    ,des_netsprcr COMMENT 'Spread Neto, campo calculado: Gross Spread - Cost of Funding. VA [[20335]]'
    ,des_tenomocr COMMENT 'Vida contractual total de la operacion por contrato. VA [[20304]]'
    ,des_rfpcr COMMENT 'En el caso del acuerdo es la solicitud de propuesta(Request For Proposal).  Campo de texto que indica Si/No. VA [[20382]]'
    ,des_avabadcr COMMENT 'Saldo Medio anual, referido al saldo medio dirigido. En DIVISA. VA [[20337]]'
    ,des_avabarcr COMMENT 'Saldo Medio anual, referido al saldo medio dirigido. En EUROS. VA [[20338]]'
    ,des_grosprcr COMMENT 'Spread bruto que se cobrarA al acuerdo. [[20307]]'
    ,des_cosfuncr COMMENT 'Coste aplicable al acuerdo de financiacion . En caso de que no se conozca, se realiza la mejor suposicion de el. [[20308]]'
    ,cod_protypss COMMENT 'Se refiere a los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-SS: 1Custody 2Depositary Services 3Paying Agency 4Transaction Serv'
    ,des_protypss COMMENT 'Se refiere a los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-SS: 1Custody 2Depositary Services 3Paying Agency 4Transaction Serv'
    ,des_ambvadss COMMENT 'Importe Final BBVA. En DIVISA. VA [[20237]]'
    ,des_ambvarss COMMENT 'Importe Final BBVA. En EUROS. VA [[20328]]'
    ,des_rfpss COMMENT 'En el caso del acuerdo es la solicitud de propuesta(Request For Proposal).  Campo de texto que indica Si/No. VA [[20382]]'
    ,des_portfdss COMMENT 'Importe total de la cartera. EN DIVISA. [[20680]]'
    ,des_portfrss COMMENT 'Importe total de la cartera. EN EUR. [[20680]]'
    ,des_devodcre COMMENT 'Importe total de la operacion. En DIVISA. VA [[20339]]'
    ,des_devorcre COMMENT 'Importe total de la operacion. En EURO. VA [[20340]]'
    ,cod_protycre COMMENT 'Codigo  de los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-SF: 1 Advisory 2 Asset Finance 3 Leveraged 4 Project 6 Other. [[20345]]'
    ,des_protycre COMMENT 'Descripcion de los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-SF: 1 Advisory 2 Asset Finance 3 Leveraged 4 Project 6 Other. [[203'
    ,des_progrcre COMMENT 'Campo automAtico que describe los diferentes grupos de productos que existen dentro de GM. [[20670]]'
    ,des_tenmocre COMMENT 'Vida contractual total de la operacion por contrato. [[20304]]'
    ,cod_disarcre COMMENT 'Codigo del equipo de ventas que pone el precio del producto. EJ: 1BOG AREA COMPLEMENTO 2BOG AREA MATFIL 3BOG AREAS APOYO 4BOG COMPLEMENTO RED 5BOG DCM ORIGINATION ... [[20672]]'
    ,des_disarcre COMMENT 'Descripcion del equipo de ventas que pone el precio del producto. [[20672]]'
    ,cod_codiscre COMMENT 'Codigo del pais del equipo de ventas que pone el precio del producto. EJ: 1BOG 2BUE 3CAR 4CHI 5CMP ... [[20671]]'
    ,des_codiscre COMMENT 'Descripcion del pais del equipo de ventas que pone el precio del producto. [[20671]]'
    ,cod_risstcre COMMENT 'Codigo de estatus dentro del flujo de trabajo de riesgo. EJ: 1Market - Valuation of product review 2Credit - Promoter applying for credit line 3Credit - In authorization with UCRC 4Credit - Amoun'
    ,des_risstcre COMMENT 'Descripcion del estatus dentro del flujo de trabajo de riesgo. [[20673]]'
    ,cod_alertcre COMMENT 'En caso de que el acuerdo este bloqueado, Codigo que se refiere al estado y a la razon de esa situacion. EJ: 1Medium - Risk 2Medium - Legal 3Medium - Taxation 4Medium - Bank 5High - Risk 6Hi'
    ,des_alertcre COMMENT 'En caso de que el acuerdo este bloqueado, describe el estado y a la razon de esa situacion. [[20674]]'
    ,cod_matficre COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. EJ: 1Yes 2No [[20675]]'
    ,des_matficre COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. [[20675]]'
    ,cod_xbordcre COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. EJ: 1Yes 2No [[20676]]'
    ,des_xbordcre COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. [[20676]]'
    ,des_devoddcm COMMENT 'Importe total de la operacion. En DIVISA. VA [[20339]]'
    ,des_devordcm COMMENT 'Importe total de la operacion. En EURO. VA [[20340]]'
    ,cod_protydcm COMMENT 'Codigo de los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-SF: 1 Advisory 2 Asset Finance 3 Leveraged 4 Project 6 Other. [[20345]]'
    ,des_protydcm COMMENT 'Descripcion de los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-SF: 1 Advisory 2 Asset Finance 3 Leveraged 4 Project 6 Other. [[203'
    ,des_progrdcm COMMENT 'Campo automAtico quedescribe los diferentes grupos de productos que existen dentro de GM. [[20670]]'
    ,des_fitaddcm COMMENT 'Comportamiento final que tendrA el banco. EN DIVISA. [[20677]]'
    ,des_fitardcm COMMENT 'Comportamiento final que tendrA el banco. EN EUR. [[20677]]'
    ,des_tenmodcm COMMENT 'Vida contractual total de la operacion por contrato. [[20304]]'
    ,cod_disardcm COMMENT 'Codigo del equipo de ventas que pone el precio del producto. EJ: 1BOG AREA COMPLEMENTO 2BOG AREA MATFIL 3BOG AREAS APOYO 4BOG COMPLEMENTO RED 5BOG DCM ORIGINATION ... [[20672]]'
    ,des_disardcm COMMENT 'Descripcion del equipo de ventas que pone el precio del producto. [[20672]]'
    ,cod_codisdcm COMMENT 'Codigo del pais del equipo de ventas que pone el precio del producto. EJ: 1BOG 2BUE 3CAR 4CHI 5CMP ... [[20671]]'
    ,des_codisdcm COMMENT 'Descripcion del pais del equipo de ventas que pone el precio del producto. [[20671]]'
    ,cod_risstdcm COMMENT 'Codigo del estatus dentro del flujo de trabajo de riesgo. EJ: 1Market - Valuation of product review 2Credit - Promoter applying for credit line 3Credit - In authorization with UCRC 4Credit - Amou'
    ,des_risstdcm COMMENT 'Descripcion del estatus dentro del flujo de trabajo de riesgo. [[20673]]'
    ,cod_alertdcm COMMENT 'En caso de que el acuerdo este bloqueado, Codigo que se refiere al estado y a la razon de esa situacion. EJ: 1Medium - Risk 2Medium - Legal 3Medium - Taxation 4Medium - Bank 5High - Risk 6Hi'
    ,des_alertdcm COMMENT 'En caso de que el acuerdo este bloqueado,Descripcion del estado y a la razon de esa situacion. [[20674]]'
    ,cod_matfidcm COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. EJ: 1Yes 2No [[20675]]'
    ,des_matfidcm COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. [[20675]]'
    ,cod_xborddcm COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. EJ: 1Yes 2No [[20676]]'
    ,des_xborddcm COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. [[20676]]'
    ,cod_robvadcm COMMENT 'Codigo de los diferentes roles que BBVA puede tener en la Operacion: 1        Sole Lead Arranger 2        Joint Lead Arranger 3        Administrative Agent 4        Documentation Agent 5        Synd'
    ,des_robvadcm COMMENT 'Descripcion de los diferentes roles que BBVA puede tener en la Operacion: 1        Sole Lead Arranger 2        Joint Lead Arranger 3        Administrative Agent 4        Documentation Agent 5'
    ,des_devodeqt COMMENT 'Importe total de la operacion. En DIVISA. VA [[20339]]'
    ,des_devoreqt COMMENT 'Importe total de la operacion. En EURO. VA [[20340]]'
    ,cod_protyeqt COMMENT 'Codigo de los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-SF: 1 Advisory 2 Asset Finance 3 Leveraged 4 Project 6 Other. [[20345]]'
    ,des_protyeqt COMMENT 'Descripcion de los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-SF: 1 Advisory 2 Asset Finance 3 Leveraged 4 Project 6 Other. [[203'
    ,des_progreqt COMMENT 'Campo automAtico que describe los diferentes grupos de productos que existen dentro de GM. [[20670]]'
    ,des_tenmoeqt COMMENT 'Descripcion de la vida contractual total de la operacion por contrato. [[20304]]'
    ,cod_disareqt COMMENT 'Codigo del equipo de ventas que pone el precio del producto. EJ: 1BOG AREA COMPLEMENTO 2BOG AREA MATFIL 3BOG AREAS APOYO 4BOG COMPLEMENTO RED 5BOG DCM ORIGINATION ...  [[20672]]'
    ,des_disareqt COMMENT 'Descripcion del equipo de ventas que pone el precio del producto. [[20672]]'
    ,cod_codiseqt COMMENT 'Codigo del pais del equipo de ventas que pone el precio del producto. EJ: 1BOG 2BUE 3CAR 4CHI 5CMP ... [[20671]]'
    ,des_codiseqt COMMENT 'Pais del equipo de ventas que pone el precio del producto. [[20671]]'
    ,cod_rissteqt COMMENT 'Codigo del estatus dentro del flujo de trabajo de riesgo. EJ: 1Market - Valuation of product review 2Credit - Promoter applying for credit line 3Credit - In authorization with UCRC 4Credit - Amou'
    ,des_rissteqt COMMENT 'Descripcion del estatus dentro del flujo de trabajo de riesgo. [[20673]]'
    ,cod_alerteqt COMMENT 'En caso de que el acuerdo este bloqueado, Codigo del estado y a la razon de esa situacion. EJ: 1Medium - Risk 2Medium - Legal 3Medium - Taxation 4Medium - Bank 5High - Risk 6High - Legal 7H'
    ,des_alerteqt COMMENT 'En caso de que el acuerdo este bloqueado, se refiere al estado y a la razon de esa situacion. [[20674]]'
    ,cod_matfieqt COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. EJ: 1Yes 2No [[20675]]'
    ,des_matfieqt COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. [[20675]]'
    ,cod_xbordeqt COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. EJ: 1Yes 2No [[20676]]'
    ,des_xbordeqt COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. [[20676]]'
    ,des_devoldfx COMMENT 'Importe total de la operacion. En DIVISA. VA [[20339]]'
    ,des_devolrfx COMMENT 'Importe total de la operacion. En EURO. VA [[20340]]'
    ,cod_protypfx COMMENT 'Codigo de los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-SF: 1 Advisory 2 Asset Finance 3 Leveraged 4 Project 6 Other. [[20345]]'
    ,des_protypfx COMMENT 'Descripcion de los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-SF: 1 Advisory 2 Asset Finance 3 Leveraged 4 Project 6 Other. [[203'
    ,des_progrofx COMMENT 'Campo automAtico que describe los diferentes grupos de productos que existen dentro de GM. [[20670]]'
    ,des_tenmonfx COMMENT 'Vida contractual total de la operacion por contrato. [[20304]]'
    ,cod_disarefx COMMENT 'Codigo del equipo de ventas que pone el precio del producto. EJ: 1BOG AREA COMPLEMENTO 2BOG AREA MATFIL 3BOG AREAS APOYO 4BOG COMPLEMENTO RED 5BOG DCM ORIGINATION ...  [[20672]]'
    ,des_disarefx COMMENT 'Descripcion del equipo de ventas que pone el precio del producto. [[20672]]'
    ,cod_coudisfx COMMENT 'Codigo de pais del equipo de ventas que pone el precio del producto. EJ: 1BOG 2BUE 3CAR 4CHI 5CMP ... [[20671]]'
    ,des_coudisfx COMMENT 'Descripcion del pais del equipo de ventas que pone el precio del producto. [[20671]]'
    ,cod_risstafx COMMENT 'Codigo del estatus dentro del flujo de trabajo de riesgo. EJ: 1Market - Valuation of product review 2Credit - Promoter applying for credit line 3Credit - In authorization with UCRC 4Credit - Amou'
    ,des_risstafx COMMENT 'Descripcion del estatus dentro del flujo de trabajo de riesgo. [[20673]]'
    ,cod_alrtafx COMMENT 'En caso de que el acuerdo este bloqueado, Codigo del estado y a la razon de esa situacion. EJ: 1Medium - Risk 2Medium - Legal 3Medium - Taxation 4Medium - Bank 5High - Risk 6High - Legal 7H'
    ,des_alertafx COMMENT 'En caso de que el acuerdo este bloqueado, describe el estado y a la razon de esa situacion. [[20674]]'
    ,cod_matfilfx COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. EJ: 1Yes 2No [[20675]]'
    ,des_matfilfx COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. [[20675]]'
    ,cod_xbordefx COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. EJ: 1Yes 2No [[20676]]'
    ,des_xbordefx COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. [[20676]]'
    ,des_devoldrt COMMENT 'Importe total de la operacion. En DIVISA. VA [[20339]]'
    ,des_devolrrt COMMENT 'Importe total de la operacion. En EURO. VA [[20340]]'
    ,cod_protyprt COMMENT 'Codigo de los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-SF: 1 Advisory 2 Asset Finance 3 Leveraged 4 Project 6 Other. [[20345]]'
    ,des_protyprt COMMENT 'Descripcion de los diferentes tipos de productos que existen, para cada uno de los productos de nivel II. Ejemplo Catalog para S&SL-SF: 1 Advisory 2 Asset Finance 3 Leveraged 4 Project 6 Other. [[203'
    ,des_progrort COMMENT 'Campo automAtico que describe los diferentes grupos de productos que existen dentro de GM. [[20670]]'
    ,des_tenmonrt COMMENT 'Vida contractual total de la operacion por contrato. [[20304]]'
    ,cod_disarert COMMENT 'Codigo del equipo de ventas que pone el precio del producto. EJ: 1BOG AREA COMPLEMENTO 2BOG AREA MATFIL 3BOG AREAS APOYO 4BOG COMPLEMENTO RED 5BOG DCM ORIGINATION ...  [[20672]]'
    ,des_disarert COMMENT 'Descripcion del equipo de ventas que pone el precio del producto. [[20672]]'
    ,cod_coudisrt COMMENT 'Codigo del pais del equipo de ventas que pone el precio del producto. EJ: 1BOG 2BUE 3CAR 4CHI 5CMP ... [[20671]]'
    ,des_coudisrt COMMENT 'Codigo del pais del equipo de ventas que pone el precio del producto. [[20671]]'
    ,cod_risstart COMMENT 'Codigo del estatus dentro del flujo de trabajo de riesgo. EJ: 1Market - Valuation of product review 2Credit - Promoter applying for credit line 3Credit - In authorization with UCRC 4Credit - Amou'
    ,des_risstart COMMENT 'Descripcion de estatus dentro del flujo de trabajo de riesgo. [[20673]]'
    ,cod_alertrt COMMENT 'En caso de que el acuerdo este bloqueado, Codigo del estado y a la razon de esa situacion. EJ: 1Medium - Risk 2Medium - Legal 3Medium - Taxation 4Medium - Bank 5High - Risk 6High - Legal 7H'
    ,des_alertrt COMMENT 'En caso de que el acuerdo este bloqueado, Descripcion del estado y a la razon de esa situacion. [[20674]]'
    ,cod_matfilrt COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. EJ: 1Yes 2No [[20675]]'
    ,des_matfilrt COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. [[20675]]'
    ,cod_xbordert COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. EJ: 1Yes 2No [[20676]]'
    ,des_xbordert COMMENT 'En caso de que el acuerdo se incluye en el proyecto Malfil. [[20676]]'
    ,des_devodecm COMMENT 'Importe total de la operacion. En DIVISA. VA [[20339]]'
    ,des_devorecm COMMENT 'Importe total de la operacion. En EURO. VA [[20340]]'
    ,des_stinpecm COMMENT 'Indice de acciones donde el cliente o la compa�ia padre cotiza. [[20664]]'
    ,des_pronaecm COMMENT 'Clave del nombre del proyecto. [[20661]]'
    ,cod_cfptyecm COMMENT 'Codigo de los diferentes tipos de productos entre CF ECM. EJ: 1IPO 2Follow-on 3ABB 4Convertible 5Agent Bank 6Fibra 7CKDs [[20662]]'
    ,des_cfptyecm COMMENT 'Descripcion de los diferentes tipos de productos entre CF ECM. [[20662]]'
    ,cod_tarcoecm COMMENT 'Codigo del pais donde se ejecuta el negocio. EJ: ABABU DHABI ADANDORRA AEUNITED ARAB EMIRATES AFAFGHANISTAN AGANTIGUA AND BARBUDA ... [[20663]]'
    ,des_tarcoecm COMMENT 'Descripcion del pais donde se ejecuta el negocio. [[20663]]'
    ,cod_cfteaecm COMMENT 'Codigo del equipo CF que estA llevando el negocio. EJ: 1Europe 2US 3China 4Chile 5Mexico 6Argentina 7Brazil 8Colombia 9Peru [[20665]]'
    ,des_cfteaecm COMMENT 'Descripcion del equipo CF que estA llevando el negocio. [[20665]]'
    ,cod_ocfteecm COMMENT 'Codigo del equipo CF que estA llevando el negocio. EJ: 1Europe 2US 3China 4Chile 5Mexico 6Argentina 7Brazil 8Colombia 9Peru [[20665]]'
    ,des_ocfteecm COMMENT 'Equipo CF que estA llevando el negocio. [[20665]]'
    ,des_refedecm COMMENT 'Cantidad total de gastos facturados al cliente mientras el negocio estA vigente. EN DIVISA. [[20667]]'
    ,des_referecm COMMENT 'Cantidad total de gastos facturados al cliente mientras el negocio estA vigente. EN EUR. [[20667]]'
    ,des_refetecm COMMENT 'Periodo de tiempo durante el cual la cantidad retenida es a cargo del cliente. [[20668]]'
    ,cod_orundecm COMMENT 'Codigo del Area del banco, que tiene su origen en el negocio. EJ: 1Client Coverage 2Corporate Lending 3Credit Portfolio Management 4Global Loan Syndications 5Global Markets 6Global Transaction'
    ,des_orundecm COMMENT 'Descripcion del Area del banco, que tiene su origen en el negocio. [[20669]]'
    ,des_undedecm COMMENT 'Importe asegurado. En DIVISA. [[20343]]'
    ,des_underecm COMMENT 'Importe asegurado. En EUR. [[20344]]'
    ,des_devoldma COMMENT 'Importe total de la operacion. En DIVISA. VA [[20339]]'
    ,des_devolrma COMMENT 'Importe total de la operacion. En EURO. VA [[20340]]'
    ,cod_cfptyma COMMENT 'Codigo de los diferentes tipos de productos entre CF ECM. EJ: 1IPO 2Follow-on 3ABB 4Convertible 5Agent Bank 6Fibra 7CKDs [[20662]]'
    ,des_cfptyma COMMENT 'Descripcion de los diferentes tipos de productos entre CF ECM. [[20662]]'
    ,cod_tarcoma COMMENT 'Codigo del pais donde se ejecuta el negocio. EJ: ABABU DHABI ADANDORRA AEUNITED ARAB EMIRATES AFAFGHANISTAN AGANTIGUA AND BARBUDA ... [[20663]]'
    ,des_tarcoma COMMENT 'Descripcion del pais donde se ejecuta el negocio. [[20663]]'
    ,cod_cfteama COMMENT 'Codigo del equipo CF que estA llevando el negocio. EJ: 1Europe 2US 3China 4Chile 5Mexico 6Argentina 7Brazil 8Colombia 9Peru [[20665]]'
    ,des_cfteama COMMENT 'Descripcion del equipo CF que estA llevando el negocio. [[20665]]'
    ,cod_ocftema COMMENT 'Codigo del equipo CF que estA llevando el negocio. EJ: 1Europe 2US 3China 4Chile 5Mexico 6Argentina 7Brazil 8Colombia 9Peru [[20665]]'
    ,des_ocftema COMMENT 'Descripcion del equipo CF que estA llevando el negocio. [[20665]]'
    ,des_refedma COMMENT 'Cantidad total de gastos facturados al cliente mientras el negocio estA vigente. EN DIVISA. [[20667]]'
    ,des_referma COMMENT 'Cantidad total de gastos facturados al cliente mientras el negocio estA vigente. EN EUR. [[20667]]'
    ,des_refetma COMMENT 'Periodo de tiempo durante el cual la cantidad retenida es a cargo del cliente. [[20668]]'
    ,cod_orundma COMMENT 'Codigo del Area del banco, que tiene su origen en el negocio. EJ: 1Client Coverage 2Corporate Lending 3Credit Portfolio Management 4Global Loan Syndications 5Global Markets 6Global Transaction'
    ,des_orundma COMMENT 'Descripcion de Area del banco, que tiene su origen en el negocio. [[20669]]'
    ,des_expproma COMMENT 'Probabilidad esperada del acuerdo. [[20720]]'
    ,cod_tarindma COMMENT 'Codigo de industria del objetivo de la empresa. EJ: 1Construction & Infra 2Consumer & Retail 3FIG 4Industrials 5Metals & Mining 6oil & Gas 7Power & Utilities 8Real Estate & Hotels 9TMT 10Ph'
    ,des_tarindma COMMENT 'Descripcion de la industria del objetivo de la empresa. [[20721]]'
    ,des_aloctema COMMENT 'Porcentaje de los honorarios de reparto asignado al equipo de plomo. [[20723]]'
    ,des_alottema COMMENT 'Porcentaje de los honorarios de reparto asignado a otro equipo que participa en la operacion. [[20724]]'
    ,des_earetdma COMMENT 'Cantidad de cuotas ya cargada al cliente. EN DIVISA. [[20722]]'
    ,des_earetrma COMMENT 'Cantidad de cuotas ya cargada al cliente. EN EUR. [[20722]]'
    ,aud_usuario COMMENT 'NOMBRE DEL PROCESO DE CARGA'
    ,aud_tim COMMENT 'FECHA DE PROCESO DE CARGA DEL REGISTRO'
	,year COMMENT 'year'
	,month COMMENT 'month'
	,day COMMENT 'day'
) COMMENT 'Descarga del fichero de oportunidades de negocio'
AS
SELECT
cod_piclient,des_piclient,des_piaccion,des_industri,des_pisector,des_paiscl,cod_pigrupo,
des_pigrupo,des_paisgrup,des_paisges,des_pisegmen,des_pisubseg,des_tier,cod_userlasm,
des_userlasm,des_fecmodu,cod_dboportu,des_tipoconf,des_nproycon,des_pipartic,cod_pubcompl,
des_catprod,des_piproduc,des_fecentr,des_feccest,cod_dvisita,des_fecvisi,des_cusebbva,
des_userbbva,des_otherusr,des_othernam,des_qnuingr,cod_pimoneda,des_feciden,des_fecdisc,
des_estgbopp,des_fecestg,des_reginal,cod_traglobb,cod_crossflg,des_crossdes,des_qnucrre,
cod_crossmod,des_qnucrrc,des_pinextst,des_fecremo,cod_userglob,cod_luserpip,des_luserpip,
des_fecmpip,cod_dpipelin,des_prodcuno,des_prodcdos,cod_psponsor,des_psponsor,cod_pdsponso,
des_pdsponso,cod_sedegeog,des_sedeg,des_fecrisk,des_fecoffe,des_fecmand,des_fecacce,des_fecmiss,
des_mainreas,des_reasonmi,des_exsystem,des_idtrade,des_qnupodc,cod_dealcurr,des_qnupocu,
des_porprob,des_qnuredc,des_qnurerc,des_fecestm,des_fecdele,cod_pipconfi,des_pipeurl,
des_updefesf,des_notdefsf,des_fihodcsf,des_fihorcsf,des_adcodcsf,des_adcorcsf,des_atandcsf,
des_atanrcsf,des_poredcsf,des_porercsf,des_pomadcsf,des_pomarcsf,des_pofedcsf,des_pofercsf,
des_todedcsf,des_todercsf,cod_prodtysf,des_protypsf,cod_tprojesf,des_typrojsf,cod_sbprodsf,
des_subprosf,des_boropnsf,cod_dstatusf,des_delstasf,cod_ascounsf,des_ascounsf,cod_bvarolsf,
des_bvrolesf,cod_astgeosf,des_astgeosf,des_desidcsf,des_desircsf,des_bbvadcsf,des_bbvarcsf,
des_avexdcsf,des_avexrcsf,des_tenorysf,des_avlifysf,des_contensf,des_relcomsf,des_chanstsf,
des_grosprsf,des_cudelsf,des_comfeesf,des_allinsf,des_rarexpsf,des_rarexssf,des_delgspsf,
des_upffedsf,des_upffeesf,des_ptfesdsf,des_ptfesesf,des_updefcsl,des_notdecsl,des_agfedcsl,
des_agfercsl,des_poredcsl,des_porercsl,des_pomadcsl,des_pomarcsl,des_pofedcsl,des_pofercsl,
des_cofedcsl,des_cofercsl,des_adfedcsl,des_adfercsl,cod_prposcsl,des_purpocsl,cod_typedcsl,
des_typdecsl,cod_numtrcsl,cod_bbvarcsl,des_bbvarcsl,cod_roluscsl,des_roluscsl,cod_origecsl,
des_orgeocsl,des_gloadcsl,des_gloarcsl,des_unwrdcsl,des_unwrrcsl,cod_dstatcsl,des_dstatcsl,
des_relcocsl,des_chastcsl,des_cosfucsl,des_roecocsl,des_totfecsl,des_avrtocsl,des_waifdcsl,
des_waifrcsl,des_alindcsl,des_alundcsl,des_rexbfcsl,des_rexpocsl,des_prifdcsl,des_prifrcsl,
des_prdgscsl,des_pdcogcsl,des_pdnescsl,cod_protystf,des_protystf,des_abvadstf,des_abvarstf,
cod_totfastf,des_totfastf,des_tofadstf,des_tofarstf,des_tofedstf,des_toferstf,des_tomadstf,
des_tomarstf,des_totinstf,des_toinrstf,des_dwpemstf,des_rpermstf,des_netspstf,cod_prty3stf,
des_prty3stf,cod_manofstf,des_manofstf,cod_accofstf,des_accofstf,cod_riscostf,des_riscostf,
des_expofstf,cod_clirostf,des_clirostf,des_conamstf,cod_bvarostf,des_bvarostf,des_posfustf,
cod_cosegstf,des_cosegstf,cod_cocoustf,des_cocoustf,cod_factystf,des_factystf,des_buyerstf,
des_repodstf,des_reporstf,cod_tyintstf,des_tyintstf,des_ratbostf,des_creagstf,des_ofmatstf,
des_grospstf,des_cosfustf,des_upfeestf,des_comfestf,des_guarastf,des_ratgustf,cod_ecanastf,
des_ecanastf,des_ecacostf,des_maecastf,cod_caristf,des_caristf,des_carmastf,des_relevstf,
des_agfeestf,des_othfestf,des_yefedstf,des_yeferstf,des_yemadstf,des_yemarstf,des_yeindstf,
des_yeinrstf,cod_funenstf,des_funenstf,des_racnnstf,des_ragrcstf,cod_rousastf,des_rousastf,
cod_prtypttf,des_prtypttf,des_abvadttf,des_abvarttf,des_netspttf,cod_prty3ttf,des_prty3ttf,
des_tenmottf,des_rfpttf,cod_courittf,des_courittf,des_arfedttf,des_arferttf,des_anridttf,
des_riferttf,des_cofedttf,des_coferttf,des_grospttf,des_anfedttf,des_anferttf,des_selerttf,
des_drapettf,des_cosfuttf,cod_clirottf,des_clirottf,des_counattf,cod_cousettf,des_cousettf,
cod_coucottf,des_coucottf,cod_bvaclttf,des_bvaclttf,des_baimdttf,cod_protypcm,des_protypcm,
des_ambvadcm,des_ambvarcm,des_netsprcm,des_rfpcm,des_avabadcm,des_avabarcm,des_grosprcm,
des_anufedcm,des_anufercm,des_implemcm,des_cosfuncm,cod_protypwk,des_protypwk,des_ambvadwk,
des_ambvarwk,des_netsprwk,des_tenomowk,des_rfpwk,des_avabadwk,des_avabarwk,des_receidwk,
des_receirwk,des_opbaldwk,des_opbalrwk,des_nurecewk,des_arrfedwk,des_arrferwk,des_risfedwk,
des_risferwk,des_comfedwk,des_comferwk,des_disfedwk,des_disferwk,des_grosprwk,des_anfeedwk,
des_anfeerwk,des_cosfunwk,cod_protypcr,des_protypcr,des_ambvadcr,des_ambvarcr,des_netsprcr,
des_tenomocr,des_rfpcr,des_avabadcr,des_avabarcr,des_grosprcr,des_cosfuncr,cod_protypss,
des_protypss,des_ambvadss,des_ambvarss,des_rfpss,des_portfdss,des_portfrss,des_devodcre,
des_devorcre,cod_protycre,des_protycre,des_progrcre,des_tenmocre,cod_disarcre,des_disarcre,
cod_codiscre,des_codiscre,cod_risstcre,des_risstcre,cod_alertcre,des_alertcre,cod_matficre,
des_matficre,cod_xbordcre,des_xbordcre,des_devoddcm,des_devordcm,cod_protydcm,des_protydcm,
des_progrdcm,des_fitaddcm,des_fitardcm,des_tenmodcm,cod_disardcm,des_disardcm,cod_codisdcm,
des_codisdcm,cod_risstdcm,des_risstdcm,cod_alertdcm,des_alertdcm,cod_matfidcm,des_matfidcm,
cod_xborddcm,des_xborddcm,cod_robvadcm,des_robvadcm,des_devodeqt,des_devoreqt,cod_protyeqt,
des_protyeqt,des_progreqt,des_tenmoeqt,cod_disareqt,des_disareqt,cod_codiseqt,des_codiseqt,
cod_rissteqt,des_rissteqt,cod_alerteqt,des_alerteqt,cod_matfieqt,des_matfieqt,cod_xbordeqt,
des_xbordeqt,des_devoldfx,des_devolrfx,cod_protypfx,des_protypfx,des_progrofx,des_tenmonfx,
cod_disarefx,des_disarefx,cod_coudisfx,des_coudisfx,cod_risstafx,des_risstafx,cod_alrtafx,
des_alertafx,cod_matfilfx,des_matfilfx,cod_xbordefx,des_xbordefx,des_devoldrt,des_devolrrt,
cod_protyprt,des_protyprt,des_progrort,des_tenmonrt,cod_disarert,des_disarert,cod_coudisrt,
des_coudisrt,cod_risstart,des_risstart,cod_alertrt,des_alertrt,cod_matfilrt,des_matfilrt,
cod_xbordert,des_xbordert,des_devodecm,des_devorecm,des_stinpecm,des_pronaecm,cod_cfptyecm,
des_cfptyecm,cod_tarcoecm,des_tarcoecm,cod_cfteaecm,des_cfteaecm,cod_ocfteecm,des_ocfteecm,
des_refedecm,des_referecm,des_refetecm,cod_orundecm,des_orundecm,des_undedecm,des_underecm,
des_devoldma,des_devolrma,cod_cfptyma,des_cfptyma,cod_tarcoma,des_tarcoma,cod_cfteama,
des_cfteama,cod_ocftema,des_ocftema,des_refedma,des_referma,des_refetma,cod_orundma,des_orundma,
des_expproma,cod_tarindma,des_tarindma,des_aloctema,des_alottema,des_earetdma,des_earetrma,aud_usuario,
aud_tim,year,month,day
FROM {rd_informacional}.tenspdpi WHERE year=$1 AND month=$2 AND day=$3 AND last_version=1